namespace SSCamIQTool.LibComm;

public enum CAMERA_MODE_TYPE
{
    CAMERA_MODE_SCL_OUT,
    CAMERA_MODE_ISP_RAW_STRM,
    CAMERA_MODE_ISP_RAW,
    CAMERA_MODE_ISP_OUT,
    CAMERA_MODE_ISP_STS,
    CAMERA_MODE_ENC_JPEG
}
