namespace SSCamIQTool.LibComm;

public enum CAMERA_CMD_TYPE
{
    CAMERA_CMD_RESERVED,
    CAMERA_CMD_CUST_DEF,
    CAMERA_CMD_SET_MODE,
    CAMERA_CMD_GET_MODE,
    CAMERA_CMD_GET_PIC,
    CAMERA_CMD_SET_API,
    CAMERA_CMD_GET_API,
    CAMERA_CMD_UPLOAD_FILE,
    CAMERA_CMD_DOWNLOAD_FILE,
    CAMERA_CMD_SET_NIR_API,
    CAMERA_CMD_GET_NIR_API
}
