namespace SSCamIQTool.LibComm;

public enum CHIP_INFO_ID
{
    eCHIP_INFO_ID_I1 = 0,
    eCHIP_INFO_ID_I3 = 1,
    eCHIP_INFO_ID_TWINKIE = 2,
    eCHIP_INFO_ID_PRETZEL = 3,
    eCHIP_INFO_ID_MACARON = 4,
    eCHIP_INFO_ID_PUDDING = 5,
    eCHIP_INFO_ID_ISPAHAN = 6,
    eCHIP_INFO_ID_IKAYAKI = 7,
    eCHIP_INFO_ID_MERCURY5 = 16,
    eCHIP_INFO_ID_TIRAMISU = 17,
    eCHIP_INFO_ID_MUFFIN = 18,
    eCHIP_INFO_ID_MOCHI = 19,
    eCHIP_INFO_ID_OPERA = 20,
    eCHIP_INFO_ID_MAX = 255
}
